services:
  mirakc:
    image: mirakc/mirakc:alpine
    container_name: mirakc
    init: true
    restart: unless-stopped
    devices:
      - /dev/dvb/adapter0/dvr0
    ports:
      - 40772:40772
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg
      - ./config.yml:/etc/mirakc/config.yml:ro
      - ./logos:/var/lib/mirakc/logos:ro
      - ./recording:/var/lib/mirakc/recording
      - ./timeshift:/var/lib/mirakc/timeshift
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
volumes:
  mirakc-epg:
    name: mirakc_epg
    driver: local
