server:
  addrs:
    - http: '0.0.0.0:40772'
tuners:
  - name: adapter0
    types: [GR]
    command: >-
      dvbv5-zap -a 0 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbt.conf
      -r -P {{{channel}}}
epg:
  cache-dir: /var/lib/mirakc/epg
filters:
  decode-filter:
    command: >-
      echo "{{{channel_type}}}/{{{channel}}} SID#{{{sid}}}"
recording:
  basedir: /var/lib/mirakc/recording
